language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost/registration_numbers

node_js:
        - "v8.10.0"

before_script:

  - psql -c 'create database registration_numbers;' -U postgres
  - psql -U postgres -d registration_numbers -a -f tables_reg_numbers.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2      